default_platform(:ios)

platform :ios do
  desc "Run swift code validation using SwiftLint"
  lane :lint do
    swiftlint(
      raise_if_swiftlint_error: true
    )
  end

  desc "Run tests"
  lane :test do
    scan(
      scheme: "Waterlove",
      skip_build: true
    )
  end

  desc "Build the project"
  lane :create_app do
    xcodebuild(
      scheme: "Waterlove",
      destination: 'generic/platform=iOS Simulator',
      clean: true,
      build: true
    )
  end
end