default_platform(:ios)

platform :ios do
  desc "Run swift code validation using SwiftLint"
  lane :lint do
    swiftlint
  end

  desc "Run tests"
  lane :test do
    scan(
      scheme: "Waterlove",
      skip_build: true,
      cloned_source_packages_path: "SourcePackages"
    )
  end

  desc "Build the project"
  lane :build do
    gym(
      scheme: "Waterlove",
      cloned_source_packages_path: "SourcePackages",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_method: "development"
    )
  end
end