name: build-app
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

  # Allows to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run lane
        run: bundle exec fastlane create_app
