name: build-app
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

  # Allows to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.3"
          bundler-cache: true
      - name: Run test lane
        run: bundle exec fastlane test